/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'global-info': GlobalInfo;
    about: About;
    bunker: Bunker;
    consultation: Consultation;
    contact: Contact;
    footer: Footer;
    homepage: Homepage;
    ira: Ira;
    service: Service;
    menu: Menu;
  };
  globalsSelect: {
    'global-info': GlobalInfoSelect<false> | GlobalInfoSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    bunker: BunkerSelect<false> | BunkerSelect<true>;
    consultation: ConsultationSelect<false> | ConsultationSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    ira: IraSelect<false> | IraSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  avatar?: (number | null) | Media;
  roles: ('admin' | 'editor' | 'user')[];
  active?: boolean | null;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Location of the media file
   */
  location: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * SEO meta title (max 60 characters)
   */
  metaTitle: string;
  /**
   * SEO meta description (max 160 characters)
   */
  metaDescription: string;
  /**
   * URL-friendly identifier (e.g., "about-us", "contact")
   */
  link: string;
  /**
   * Page content components
   */
  components?:
    | (
        | {
            title?: string | null;
            /**
             * Edit content using the markdown editor with toolbar and preview. Content is stored as markdown.
             */
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown-with-title';
          }
        | {
            title: string;
            questions?:
              | {
                  question: string;
                  /**
                   * Answer content (stored as markdown)
                   */
                  answerMarkdown: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  /**
   * Hide this page from site index/search
   */
  hideFromIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  roles?: T;
  active?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  link?: T;
  components?:
    | T
    | {
        'markdown-with-title'?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answerMarkdown?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  hideFromIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site information and branding
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-info".
 */
export interface GlobalInfo {
  id: number;
  /**
   * Site logo
   */
  logo: number | Media;
  /**
   * Mask image for branding
   */
  maskImage: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * About page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Hero banner image for the about page
   */
  heroBannerImage: number | Media;
  markdownSection: {
    /**
     * Section subtitle
     */
    subtitle?: string | null;
    /**
     * Section title
     */
    title?: string | null;
    /**
     * Markdown content
     */
    markdownContent: string;
    button: {
      button: {
        title: string;
        url: string;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }[];
  };
  quotationSection: {
    /**
     * Quotation text
     */
    quote: string;
    /**
     * Quote author
     */
    author: string;
    /**
     * Main quotation image
     */
    image: number | Media;
    /**
     * Additional image (optional)
     */
    additionalImage?: (number | null) | Media;
    /**
     * Mobile-specific image (optional)
     */
    mobileImage?: (number | null) | Media;
    button?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bunker page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bunker".
 */
export interface Bunker {
  id: number;
  header: {
    pageHeader: {
      subtitle: string;
      title: string;
      description?: string | null;
    };
    primaryButton: {
      button: {
        title: string;
        url: string;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }[];
    secondaryButton: {
      button: {
        title: string;
        url: string;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }[];
    headerImage: number | Media;
    list: {
      heading: string;
      description?: string | null;
      id?: string | null;
    }[];
  };
  howItWorks: {
    title: string;
    /**
     * List of benefits
     */
    list: {
      heading: string;
      description?: string | null;
      id?: string | null;
    }[];
  };
  pricing: {
    title: string;
    description: string;
    subtitle: string;
    metalRates: {
      /**
       * Minimum value
       */
      min: number;
      /**
       * Maximum value
       */
      max: number;
      /**
       * Allocated rate
       */
      allocatedRate: number;
      /**
       * Segregated rate
       */
      segregatedRate: number;
      id?: string | null;
    }[];
  };
  whyBattalionBunker: {
    title: string;
    description: string;
    button: {
      button: {
        title: string;
        url: string;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }[];
    list: {
      heading: string;
      description: string;
      icon: number | Media;
      id?: string | null;
    }[];
  };
  /**
   * FAQ section with questions and answers
   */
  faq: {
    title: string;
    questions?:
      | {
          question: string;
          /**
           * Answer content (stored as markdown)
           */
          answerMarkdown: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'faq';
  }[];
  consultationsCTA: {
    title: string;
    primaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    secondaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    description: string;
  };
  comparison: {
    title: string;
    tableHeader: {
      heading_1: string;
      heading_2: string;
      heading_3: string;
      heading_4: string;
    };
    tableBody: {
      feature: string;
      battalionBunker: 'Yes' | 'No';
      legacyStorage: 'Yes' | 'No';
      homeStorage: 'Yes' | 'No';
      id?: string | null;
    }[];
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Consultation page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation".
 */
export interface Consultation {
  id: number;
  heading: {
    pageHeader: {
      subtitle: string;
      title: string;
      description?: string | null;
    };
    linkCard: {
      title: string;
      image: number | Media;
      description: string;
      link: string;
      linkTitle?: string | null;
      id?: string | null;
    }[];
  };
  information?: {
    title?: string | null;
    description?: string | null;
    items?:
      | {
          heading: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading: {
    heading: string;
    description: string;
    id?: string | null;
  };
  /**
   * Contact details and information
   */
  contactDetails?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site footer content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer logo
   */
  logo: number | Media;
  socials?: {
    instagram?: string | null;
    youtube?: string | null;
    x?: string | null;
    tiktok?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
  };
  menuColumns?:
    | {
        title?: string | null;
        items?:
          | {
              item: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    banner: number | Media;
    mobileBanner?: (number | null) | Media;
    title: string;
    description: string;
    primaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    secondaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    checklist?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  quotation: {
    /**
     * Quotation text
     */
    quote: string;
    /**
     * Quote author
     */
    author: string;
    /**
     * Main quotation image
     */
    image: number | Media;
    /**
     * Additional image (optional)
     */
    additionalImage?: (number | null) | Media;
    /**
     * Mobile-specific image (optional)
     */
    mobileImage?: (number | null) | Media;
    button?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  companyInfo: {
    subTitle?: string | null;
    title: {
      title: string;
      id?: string | null;
    }[];
    /**
     * Max 500 characters
     */
    description: string;
    sliderItems: {
      title: string;
      description: string;
      linkText?: string | null;
      linkUrl?: string | null;
      image: number | Media;
      id?: string | null;
    }[];
  };
  howItWorks: {
    title: string;
    list: {
      heading: string;
      description: string;
      id?: string | null;
    }[];
    backgroundImage: number | Media;
  };
  comparison: {
    title: string;
    /**
     * Max 500 characters
     */
    description: string;
    link?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    battalionPros: {
      heading: string;
      description: string;
      id?: string | null;
    }[];
    otherCons: {
      heading: string;
      description: string;
      id?: string | null;
    }[];
    logo?: (number | null) | Media;
    backgroundImage?: (number | null) | Media;
  };
  productSlider: {
    title: string;
    description: string;
    link: {
      button: {
        title: string;
        url: string;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }[];
  };
  newsletter: {
    heading: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * IRA page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ira".
 */
export interface Ira {
  id: number;
  header: {
    pageHeader: {
      subtitle: string;
      title: string;
      description?: string | null;
    };
    image: number | Media;
  };
  whyUs: {
    title: string;
    description: string;
    image: number | Media;
    list: {
      heading: string;
      description: string;
      id?: string | null;
    }[];
  };
  benefits: {
    title: string;
    /**
     * List of benefits
     */
    list: {
      heading: string;
      description?: string | null;
      id?: string | null;
    }[];
  };
  howToGetStarted: {
    title: string;
    /**
     * List of benefits
     */
    list: {
      heading: string;
      description?: string | null;
      id?: string | null;
    }[];
  };
  consultationsCTA: {
    title: string;
    primaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    secondaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    description: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Services page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: number;
  header: {
    pageHeader: {
      subtitle: string;
      title: string;
      description?: string | null;
    };
    linkCard: {
      title: string;
      image: number | Media;
      description: string;
      link: string;
      linkTitle?: string | null;
      id?: string | null;
    }[];
  };
  consultations: {
    title: string;
    description: string;
    image: number | Media;
    list: {
      heading: string;
      description: string;
      id?: string | null;
    }[];
  };
  consultationsCTA_1: {
    title: string;
    primaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    secondaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    description: string;
  };
  secureStorage: {
    title: string;
    description: string;
    image: number | Media;
    list: {
      heading: string;
      description: string;
      id?: string | null;
    }[];
  };
  ira: {
    title: string;
    description: string;
    image: number | Media;
    list: {
      heading: string;
      description?: string | null;
      id?: string | null;
    }[];
    button: {
      button: {
        title: string;
        url: string;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'button';
    }[];
    mobileImage?: (number | null) | Media;
  };
  consultationsCTA_2: {
    title: string;
    primaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    secondaryButton?:
      | {
          button: {
            title: string;
            url: string;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    description: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site navigation menu configuration. Supports nested submenus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  /**
   * Menu title (for admin reference only)
   */
  title: string;
  /**
   * Main navigation menu items. Supports nested submenus.
   */
  items?:
    | {
        /**
         * Display order (lower numbers appear first)
         */
        order?: number | null;
        /**
         * Menu item label
         */
        title: string;
        /**
         * Link URL (e.g., "/about", "https://example.com", or leave empty for parent items)
         */
        url?: string | null;
        /**
         * Link target behavior
         */
        target?: ('_self' | '_blank' | '_parent' | '_top') | null;
        /**
         * Optional image for the menu item (matches Strapi custom_image extension)
         */
        customImage?: (number | null) | Media;
        /**
         * Nested menu items (Level 2 of 3)
         */
        childrens?:
          | {
              /**
               * Display order (lower numbers appear first)
               */
              order?: number | null;
              /**
               * Menu item label
               */
              title: string;
              /**
               * Link URL (e.g., "/about", "https://example.com", or leave empty for parent items)
               */
              url?: string | null;
              /**
               * Link target behavior
               */
              target?: ('_self' | '_blank' | '_parent' | '_top') | null;
              /**
               * Optional image for the menu item (matches Strapi custom_image extension)
               */
              customImage?: (number | null) | Media;
              /**
               * Nested menu items (Level 3 of 3)
               */
              subItems?:
                | {
                    /**
                     * Display order (lower numbers appear first)
                     */
                    order?: number | null;
                    /**
                     * Menu item label
                     */
                    title: string;
                    /**
                     * Link URL (e.g., "/about", "https://example.com", or leave empty for parent items)
                     */
                    url?: string | null;
                    /**
                     * Link target behavior
                     */
                    target?: ('_self' | '_blank' | '_parent' | '_top') | null;
                    /**
                     * Optional image for the menu item (matches Strapi custom_image extension)
                     */
                    customImage?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-info_select".
 */
export interface GlobalInfoSelect<T extends boolean = true> {
  logo?: T;
  maskImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroBannerImage?: T;
  markdownSection?:
    | T
    | {
        subtitle?: T;
        title?: T;
        markdownContent?: T;
        button?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  quotationSection?:
    | T
    | {
        quote?: T;
        author?: T;
        image?: T;
        additionalImage?: T;
        mobileImage?: T;
        button?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bunker_select".
 */
export interface BunkerSelect<T extends boolean = true> {
  header?:
    | T
    | {
        pageHeader?:
          | T
          | {
              subtitle?: T;
              title?: T;
              description?: T;
            };
        primaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        headerImage?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        title?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        title?: T;
        description?: T;
        subtitle?: T;
        metalRates?:
          | T
          | {
              min?: T;
              max?: T;
              allocatedRate?: T;
              segregatedRate?: T;
              id?: T;
            };
      };
  whyBattalionBunker?:
    | T
    | {
        title?: T;
        description?: T;
        button?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        faq?:
          | T
          | {
              title?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answerMarkdown?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  consultationsCTA?:
    | T
    | {
        title?: T;
        primaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        description?: T;
      };
  comparison?:
    | T
    | {
        title?: T;
        tableHeader?:
          | T
          | {
              heading_1?: T;
              heading_2?: T;
              heading_3?: T;
              heading_4?: T;
            };
        tableBody?:
          | T
          | {
              feature?: T;
              battalionBunker?: T;
              legacyStorage?: T;
              homeStorage?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation_select".
 */
export interface ConsultationSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        pageHeader?:
          | T
          | {
              subtitle?: T;
              title?: T;
              description?: T;
            };
        linkCard?:
          | T
          | {
              title?: T;
              image?: T;
              description?: T;
              link?: T;
              linkTitle?: T;
              id?: T;
            };
      };
  information?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        heading?: T;
        description?: T;
        id?: T;
      };
  contactDetails?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  socials?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        x?: T;
        tiktok?: T;
        linkedin?: T;
        facebook?: T;
      };
  menuColumns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              item?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        banner?: T;
        mobileBanner?: T;
        title?: T;
        description?: T;
        primaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        checklist?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  quotation?:
    | T
    | {
        quote?: T;
        author?: T;
        image?: T;
        additionalImage?: T;
        mobileImage?: T;
        button?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  companyInfo?:
    | T
    | {
        subTitle?: T;
        title?:
          | T
          | {
              title?: T;
              id?: T;
            };
        description?: T;
        sliderItems?:
          | T
          | {
              title?: T;
              description?: T;
              linkText?: T;
              linkUrl?: T;
              image?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        title?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  comparison?:
    | T
    | {
        title?: T;
        description?: T;
        link?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        battalionPros?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
        otherCons?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
        logo?: T;
        backgroundImage?: T;
      };
  productSlider?:
    | T
    | {
        title?: T;
        description?: T;
        link?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  newsletter?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ira_select".
 */
export interface IraSelect<T extends boolean = true> {
  header?:
    | T
    | {
        pageHeader?:
          | T
          | {
              subtitle?: T;
              title?: T;
              description?: T;
            };
        image?: T;
      };
  whyUs?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  howToGetStarted?:
    | T
    | {
        title?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  consultationsCTA?:
    | T
    | {
        title?: T;
        primaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  header?:
    | T
    | {
        pageHeader?:
          | T
          | {
              subtitle?: T;
              title?: T;
              description?: T;
            };
        linkCard?:
          | T
          | {
              title?: T;
              image?: T;
              description?: T;
              link?: T;
              linkTitle?: T;
              id?: T;
            };
      };
  consultations?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  consultationsCTA_1?:
    | T
    | {
        title?: T;
        primaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        description?: T;
      };
  secureStorage?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  ira?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        list?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
        button?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        mobileImage?: T;
      };
  consultationsCTA_2?:
    | T
    | {
        title?: T;
        primaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        secondaryButton?:
          | T
          | {
              button?:
                | T
                | {
                    button?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        order?: T;
        title?: T;
        url?: T;
        target?: T;
        customImage?: T;
        childrens?:
          | T
          | {
              order?: T;
              title?: T;
              url?: T;
              target?: T;
              customImage?: T;
              subItems?:
                | T
                | {
                    order?: T;
                    title?: T;
                    url?: T;
                    target?: T;
                    customImage?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}